apiVersion: cloud.google.com/v1
kind: BackendConfig # https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features
metadata:
  name: websocket-config
  labels:
    {{- include "chips-websocket.labels" . | nindent 4 }}
spec:
  timeoutSec: 3600
  connectionDraining:
    drainingTimeoutSec: 3600
  sessionAffinity:
    affinityType: "CLIENT_IP"