kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-config" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "tplValues.render" ( dict "value" .Values.commonLabels "scope" $ ) | nindent 4 }}
    {{- end }}
data:
  config: |
    :site:
      :host: <%= ENV['ONETIMESECRET_HOST'] || 'localhost:3000' %>
      :domain: <%= ENV['ONETIMESECRET_HOST'] || 'localhost' %>
      :ssl: <%= ENV['ONETIMESECRET_SSL'] == 'true' %>
      :secret: <%= ENV['ONETIMESECRET_SECRET'] || 'CHANGEME' %>
    :redis:
      :uri: <%= (ENV['ONETIMESECRET_REDIS_URL'] || 'redis://redis:6379/0') + '?timeout=10&thread_safe=false&logging=false' %>
    {{- if .Values.configuration.colonels }}
    :colonels:
      {{- range $value := split "," .Values.configuration.colonels }}
      - {{ $value }}
      {{- end }}
    {{- end }}
    {{- if not (or .Values.configuration.emailer.sendgridEnabled .Values.configuration.emailer.smtpEnabled) }}
    :emailer:
      mode: :sendgrid
      account: CHANGEME
      password: CHANGEME
      from: CHANGEME@example.com
      fromname: CHANGEME
    {{- else if .Values.configuration.emailer.sendgridEnabled }}
    :emailer:
      :mode: :sendgrid
      :account: {{ .Values.configuration.emailer.sendgridAccount }}
      :password: {{ .Values.configuration.emailer.sendgridPassword }}
      :from: {{ default "CHANGEME@example.com" .Values.configuration.emailer.from }}
      :fromname: {{ .Values.configuration.emailer.sendgridFromName }}
      :bcc: {{ .Values.configuration.emailer.sendgridBcc }}
    {{- else if .Values.configuration.emailer.smtpEnabled }}
    :emailer:
      :mode: :smtp
      :from: {{ default "CHANGEME@example.com" .Values.configuration.emailer.from }}
      :host: {{ .Values.configuration.emailer.smtpHost }}
      :port: {{ .Values.configuration.emailer.smtpPort }}
      :tls: {{ .Values.configuration.emailer.smtpTls }}
      :user: {{ .Values.configuration.emailer.smtpUser }}
      :pass: {{ .Values.configuration.emailer.smtpPass }}
      :auth: {{ default "plain" .Values.configuration.emailer.smtpAuth }}
    {{- end }}
    {{- if .Values.configuration.incoming.enabled }}
    {{- toYaml .Values.configuration.incoming | nindent 4 }}
    {{- end }}
    :locales:
      - en
      - es
      - de
      - nl
      - ru
      - cs
      - fr
      - bg
      - tr
      - ca_ES
      - pt_BR
      - pl
      - it_IT
      - cn
      - el_GR
      - sl_SI
    :unsupported_locales:
      - jp
    :stathat:
      :enabled: false
      :apikey: CHANGEME
      :default_chart: CHANGEME
    :text:
      :nonpaid_recipient_text: 'You need to create an account!'
      :paid_recipient_text: 'Send the secret link via email'
    :limits:
      :create_secret: 250
      :create_account: 10
      :update_account: 10
      :email_recipient: 50
      :send_feedback: 10
      :authenticate_session: 5
      :homepage: 500
      :dashboard: 1000
      :failed_passphrase: 5
      :show_metadata: 1000
      :show_secret: 1000
      :burn_secret: 1000
