{{- if .Values.ingress.enabled }}
kind: Ingress
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplValues.render" ( dict "value" .Values.commonLabels "scope" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.ingress.customAnnotations }}
  annotations: {{- toYaml .Values.ingress.customAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
  {{- if .Values.ingress.tls.hosts }}
    {{- range $value := split "," .Values.ingress.tls.hosts }}
    - {{ $value }}
    {{- end }}
  {{- else }}
    - {{ .Values.configuration.host }}
  {{- end }}
    secretName: {{ printf "%s-tls" (default .Values.configuration.host .Values.ingress.tls.secretName) | replace "." "-" }}
  {{- end }}
  rules:
  {{- if .Values.ingress.customRules }}
    {{- toYaml .Values.ingress.customRules | nindent 2 }}
  {{- else }}
  - host: {{ default .Values.configuration.host .Values.ingress.rules.host }}
    http:
      paths:
      - path: {{ default "/" .Values.ingress.rules.path }}
        pathType: {{ default "Exact" .Values.ingress.rules.pathType }}
        backend:
          service:
            name: {{ default (include "common.names.fullname" .) .Values.ingress.rules.serviceName }}
            port:
              number: {{ default .Values.networkPort .Values.ingress.rules.servicePort }}
  {{- end }}
{{- end }}
