kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplValues.render" ( dict "value" .Values.commonLabels "scope" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  secret: {{- if not (empty .Values.configuration.secret) }}
    {{- .Values.configuration.secret | nindent 4}}
    {{- end -}}

