kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplValues.render" ( dict "value" .Values.commonLabels "scope" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  CIRCLECI_API_TOKEN: {{ required "A CircleCI API token must be set in values.yaml" .Values.configuration.circleCiApiToken }}
  GOGO_LITA_SLACK_TOKEN: {{ required "A Slack token must be set in values.yaml" .Values.configuration.slackToken }}
